### ISSUE TITLE
input capture

### ISSUE THREAD

**Issue by EthanGroat** [tavurth/godot-simple-fps-camera#3]
Running on Windows 8.1,
The mouse and keyboard were locked to the window and kept resetting position. The Windows allow access screen popped up and I could not focus on it.

**Comment by tavurth** [comment]
Hi @CracklingBacon! 

Thank you for your bug report, I've created a PR which should resolve your issue.
Could you try pulling directly from this github repository and then reloading Godot?

**Comment by EthanGroat** [comment]
It works!  Mouse is free to go where it pleases, however turning is now limited to as far as the mouse goes over the screen.  As an aside, it would be interesting to see if the mouse's input velocity could be captured, rather than its actual change in position onscreen.  I'm a newcomer to Godot so I'm not sure how to do it.  Anyway, it's a good thing the mouse is free to roam!
