### ISSUE TITLE
added smoothing if anyone is interested

### ISSUE THREAD

**Issue by Form2** [tavurth/godot-simple-fps-camera#5]
feel free to add it to the example project:

[Camera.txt](https://github.com/tavurth/godot-simple-fps-camera/files/7837858/Camera.txt)

never posted an issue before, probably did everything wrong :)

**Comment by Form2** [comment]
`extends Camera

func interp(current, target, speed, step):
	return current + (target - current) * (speed * step)
	
var mouse_x = 0.0; var mouse_y = 0.0
var yaw = 0.0; var pitch = 0.0
	
func _process(delta):
	# interp last values to mouse current values
	yaw = interp(yaw, mouse_x, 15, delta)
	pitch = interp(pitch, mouse_y, 15, delta)
	# update yaw
	get_parent().set_rotation(get_parent().get_rotation() + Vector3(0, -yaw * delta, 0))
	# update pitch
	var new_rotation = self.get_rotation() + Vector3(-pitch * delta, 0, 0)
	new_rotation.x = clamp(new_rotation.x, PI / -2, PI / 2)
	self.set_rotation(new_rotation)
	# reset mouse
	mouse_x = 0; mouse_y = 0
	
func _ready():
	set_process_input(true)
	
func _input(event):
	if event is InputEventMouseMotion:
		mouse_x = event.relative.x
		mouse_y = event.relative.y

func _enter_tree():
	Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

func _leave_tree():
	Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)`

**Comment by tavurth** [comment]
Hi @Form2, thank you for the issue!

If you would like to make changes normally you'd create a `Pull Request` to this repository. 

To do that you click `fork` at the top-right, this will create a copy for you to make changes.

You can then push your changes to that version (your version).

From there you can click `Pull Requests` and create a new one back to this repository.

You can find [more information here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by tavurth** [comment]
In regards to adding interpolation, I tried to keep this repository as clean and simple as possible so that people can learn quickly how it works.

Perhaps adding an option to the camera, or showing a label ("Shift to interpolate") would be more useful?

**Comment by Form2** [comment]
I thought you might be trying to keep it free of unnecessary stuff, and thanks for the info. It's there if anyone wants it :)

**Comment by tavurth** [comment]
Because you commented I went through and polished things up a bit, I added player controls also (WASD)

**Comment by Form2** [comment]
Since you're looking at the project, I wanted to mention that I only posted the interpolation script as an issue because the page where I found the project (within the Godot projects browser) linked to the repository's issues page. Just saying because I feel stupid having created an issue for no reason :)

Thanks for being nice and have a good day.
