### ISSUE TITLE
How can I use a projection image in the flashlight?

### ISSUE THREAD

**Issue by MasterDingo** [tavurth/godot-simple-fps-camera#7]
Is it possible to set a texture or sprite to be projected onto the scene from the flashlight?

**Comment by tavurth** [comment]
Hi, you could try checking out this commit where I did just that
https://github.com/tavurth/godot-simple-fps-camera/commit/ccb3793c1ada219bfad6835ddbc82dd4952719b8

However Godot 3.x doesn't really support that well 😞

**Comment by MasterDingo** [comment]
Thank you so much!
