### ISSUE TITLE
godot 4

### ISSUE THREAD

**Issue by ghost** [tavurth/godot-simple-fps-camera#8]
Hi

Can you please make a branch for godot 4?
Godot 4 is in beta and soon will be released.

**Comment by tavurth** [comment]
Hey I'm a little swamped with things to do at the moment.

However this code should be entirely portable, did you try opening the project in the Godot 4 editor yet?

The code is also fairly commented as I intended this as a learning exercise, if you read through it I guess it should be easy to see how it works.

I will get around to porting everything to 4.x but most likely a little after 4.x is finally released and stable.

**Comment by C-Corgi** [comment]
Fixed in #12

**Comment by tavurth** [comment]
Needs a _liittle_ more work

**Comment by tavurth** [comment]
@C-Corgi merged
